[package]
name = "binance-auto-sell"
version = "0.1.0"
authors = ["Wink Saville <wink@saville.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.2", features = ["json"] }
tokio = { version = "1.5.0", features = ["full"] }
serde = { version = "1.0.125", features = ["derive"] }
env_logger = "0.8.3"
log = "0.4.14"
serde_json = "1.0.64"
strum_macros = "0.20.1"
clap = "2.33.3"
hmac = "0.10.1"
sha2 = "0.9.3"
hex-literal = "0.3.1"
chrono = "0.4.19"
hex = "0.4.3"
rust_decimal = { version = "1.12.4", features = ["serde-arbitrary-precision"] }
rust_decimal_macros = "1.12.4"
test-env-log = "0.2.7"
toml = "0.5.8"
semver = { version = "0.11.0", features = ["serde"] }
lazy_static = "1.4.0"

[dev-dependencies]
assert_cmd = "1.0.3"
predicates = "1.0.7"

[build-dependencies]
vergen = "5.1.8"
