[package]
name = "binance-auto-sell"
version = "0.1.0"
authors = ["Wink Saville <wink@saville.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.2", features = ["json"] }
tokio = { version = "1.5.0", features = ["full"] }
serde = { version = "1.0.125", features = ["derive"] }
env_logger = "0.8.3"
log = "0.4.14"
serde_json = "1.0.64"
strum_macros = "0.20.1"
structopt = "0.3.21"
clap = "2.33.3"
#clap = "3.0.0-beta.2" # 3.0.0-beta.2 didn't with sec_key and api_key optional

[dev-dependencies]
assert_cmd = "1.0.3"
predicates = "1.0.7"
