[package]
name = "binance-cli"
version = "0.3.0"
authors = ["Wink Saville <wink@saville.com>"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.4", features = ["json"] }
tokio = { version = "1.12.0", features = ["full"] }
serde = { version = "1.0.130", features = ["derive"] }
env_logger = "0.9.0"
log = "0.4.14"
serde_json = "1.0.68"
strum_macros = "0.22.0"
clap = "2.33.3"
hmac = "0.11.0"
sha2 = "0.9.8"
hex-literal = "0.3.3"
chrono = "0.4.19"
hex = "0.4.3"
rust_decimal = { version = "1.16.0", features = ["serde-arbitrary-precision"] }
rust_decimal_macros = "1.16.0"
test-env-log = "0.2.7"
toml = "0.5.8"
semver = { version = "1.0.4", features = ["serde"] }
lazy_static = "1.4.0"
rusty-money = "0.4.1"
separator = "0.4.1"
openssl = { version = "0.10", features = ["vendored"] }
openssl-probe = "0.1.2"


[dev-dependencies]
assert_cmd = "2.0.2"
predicates = "2.0.3"

[build-dependencies]
vergen = "5.1.17"
