# This file contains configuration information for binance_cli.
# Of particular importance is that it may contian your binance keys.
# As such you should NEVER EVER add real keys to this particular
# file as in its default location, the root of the project, it is
# saved to the source control system and is public!
#
# The easiest thing to do is to copy this file to configs/ directory
# and then modify that copy to your liking. Copying to configs/ is
# is convenient because configs/ is the default location that the program
# looks for this file.  You can move it to some other directory and
# then create a BINANCE_CONFIG environment variable with the full path
# to that file.
#
# For instance:
#    $ cp config.toml /home/wink/wink-binance-config.toml
#    $ export BINANCE_CONFIG=/home/wink/wink-binance-config.toml
#
# Or you can use the `--config path-to-file` or `-c path-to-file`
# as a final option.
#
# Note: the reason configs/ is ok is that by default `configs/`
# and data*/ are not saved to the source control system.
# See .gitignore for other ignored items.

# Add your "real" api-key here or use --api-key="xxx" cli option
# or set BINANCE_API_KEY environment variable.
API_KEY = "an api key"

# Add your "real" secret-key here or use --secret-key="xxx" cli option
# or set BINANCE_SECRET_KEY environment variable.
SECRET_KEY = "a secret key"

# Path and file name for the log file. This log file contians information
# about each trade that is made.
order_log_path = "data/an_order_log.txt"

# The name of the asset that is used to buy or sell another asset.
default_quote_asset = "USD"

# Test mode "true" | "false". The default is currently true so
# trade commands such as auto-buy, auto-sell, buy-market, buy-market-value,
# sell-market and sell-market-value do nothing. My suggestion is
# to leave this `test = true` and when you're ready to do a trade
# pass the `--no-test` flag on the command line. In anycase I cannot
# stress enough this program is DANGEROUS.
test = true

# confirmation_required "true" | "false"
# Default is true so auto-buy and auto-sell require confirmation and
# the program will prompt the user. The program will only continue if
# "Yes" is typed without the quotes. My suggestion is to leave this
# `confirmation_required = true` and when in a daemon mode or run via
# a script then pass the --no-confirmation_required on the command line.
# AGAIN BE VERY CAREFUL!
confirmation_required = true

# Default scheme for make_url
scheme = "https"

# Default domain for make_url, binance.us or binance.com
domain = "binance.us"

# The "auto-sell" subcommand uses the "keep" entries asset
# as a list of assets to keep, if an asset isn't listed
# it will be SOLD, BE VERY CAREFUL!
#
# Each "keep" entry is the name of a coin to
# keep at least some. Each entry can have
# 1 to 3 fields; name, min, quote_asset:
#   name: must be present.
#   min: is the minimum number of coins to keep.
#   quote_asset: can override the default_quote_asset
#
# A complete example is "BNB" below where at least 510
# BNB is kept and the rest is sold for USDT (BNBUSDT).
#
# ONE at least 100 coins are kept using the default_quote_asset
# and finaly "all" of ADA is sold. Note: because of minimums
# there is likely some "dust" (a small fractional amount) unsold.
keep = [
    #{ name = "BNB", min = 510, quote_asset = "USDT" },
    #{ name = "ONE", min = 100 },
    #{ name = "ADA" },  # Comments may follow fields

    # So we don't accidentally use this file
    this will generate an error. Delete or comment out.
]

# The "auto-buy" subcommand uses the "buy" as a list of assets
# to buy. It buys approximately ((percent / 100) * quote_asset)
# "free" (i.e. unlocked) quote_asset.
#
# It consits of 3 fields; name, percent and quote_asset:
#   name: must be present.
#   percent: percentage of the quote_asset that will be
#            used to by the named asset above.
#   quote_asset: is the asset to use to buy, it overrides
#            the default_quote_asset
#
# So MATIC is bought using 10% of the currently free USD.
# and what percentage of that quote
#
# Note: 
buy = [
    #{ name = "MATIC", percent = 10, quote_asset = "USD" },
    #{ name = "ZEN", percent = 15 }

    # So we don't accidentally use this file
    this will generate an error. Delete or comment out.
]